# Generated by Django 3.0.2 on 2020-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=30)),
                ('openingbal', models.CharField(max_length=14)),
                ('mobilenumber', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=30)),
                ('narration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=30)),
                ('openingbal', models.CharField(max_length=14)),
                ('mobilenumber', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=30)),
                ('narration', models.CharField(max_length=30)),
            ],
        ),
    ]
