# Generated by Django 3.0.2 on 2020-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=30)),
                ('balbefore', models.CharField(max_length=14)),
                ('balafter', models.CharField(max_length=14)),
                ('dateoftran', models.CharField(max_length=16)),
                ('crdr', models.CharField(max_length=2)),
                ('narration', models.CharField(max_length=30)),
            ],
        ),
    ]
